### ISSUE TITLE
[PE-D][Tester C] Edit success message despite not entering any optional field

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-3/tp#195]
![Screenshot 2023-11-03 at 4.25.31 PM.png](https://raw.githubusercontent.com/vivienherq/ped/main/files/bc9112dc-1f34-4f65-b70f-af7c85becdb0.png)

I only entered `edit 4` into the command line, but received the 'Edit Success' message.

This occurs only occasionally for some indexes, and only once for those indexes (when I key in edit 4 again, the error is somehow not there anymore).

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: vivienherq/ped#4

**Comment by HollaG** [comment]
Reproductive steps
1. Delete all json storage files
2. Run the app
3. type `list students`
4. Type `edit 4`
- Expected: Error message, saying no fields edit
- Actual: Edited success
5. Type `edit 4` again
- Expected (and actual): Error message, saying no fields edited

This occurs because the first `edit 4` delets the email and address fields, which is considered a success.

Should this be the case?
