### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by yiwen101** [AY2324S1-CS2103T-T11-3/tp#58]
Despite the visible efforts from the ab3 group in applying software principle by modularizing things and breaking them into multiple abstraction layers, it turns out that the current extensibility still sucks, as very often a minor modification leads to ripple effects and modification across the code base. 

It remain a long term task to refractor current code base and improve its clarity and extensibility.

**Comment by HollaG** [comment]
Task 1: 
`JsonAdaptedPerson.java` constructor doesn't do abstraction very well. 
1. Change all Person Class fields e.g. Address, Name to private
2. Have such fields implement a PersonProperty interface with the following methods:
a. serialize() // serializes the field into a string
b. deserialize() // return a PersonProperty object with the correct data values

Point 2b also lets use change the toModelType() method in JsonAdaptedPerson to use that function, instead of calling a constructor.
This is needed because the current way assumes the way we store items in the JSON file is the same as when a user enters it, which might not always be true.
